const categories = [
  { id: "17nVOT5D8GwMDMxkajvk", name: "Library" },
  { id: "1iQQAsjDQBjnajnetubi", name: "Beauty and Personal Care" },
  { id: "1paZpqneVgsJTte2hLnk", name: "Sports, Gym and Fitness" },
  { id: "22LPOIrLUGOyzagrydsQ", name: "Safety and Hygiene Essentials" },
  { id: "2RMhDFr1b4DKpDNNLJUS", name: "Medical Supplies" },
  { id: "3l5pFPAHeKwjTxl7MGCn", name: "Electrical Services" },
  { id: "3zyNbh8rtQxNSjGpFTCz", name: "Legal Services" },
  { id: "5NUmSCZejdKez5fugpj7", name: "Distributor" },
  { id: "5mfZSyE1OVH0NrHnUVpf", name: "Movies" },
  { id: "6aJeGFItdQbbsWmdDkTC", name: "Graphics and Design" },
  { id: "7H4Qr4HGBHnioqqOrLxj", name: "Storage and Organizer" },
  { id: "8H8QzB3aYnBYBviMneef", name: "Humor" },
  { id: "8T0lvWeGmJSLVNIhuIQN", name: "Development and IT" },
  { id: "8bvfoH95ktMjCWB8bpos", name: "Gardening" },
  { id: "8k4Bx8WbO7tzbEbwBtPv", name: "Marketing " },
  { id: "AX9QsJhpFZczCDDAnelJ", name: "Exporter" },
  { id: "BUqOqvewdCqisoYZE5cA", name: "Wholesaler" },
  { id: "CSSC68mbtAJxpTSut55i", name: "Restaurant" },
  { id: "DDtb2VDo50ZdKdGvoxii", name: "Clothing Accessories" },
  { id: "EwGj5AfDyLkGGr1mJ9VV", name: "Media and Entertainment" },
  { id: "F8FWqQyC1KYbTgjrZzSC", name: "Organic Products" },
  { id: "FBOIGId8pJFI9wgOx", name: "Footwear" },
  { id: "FHm6QoiDq2x27vwna", name: "Clothing" },
  { id: "G3yj06n5XPgC0vXJhWlk", name: "Agriculture" },
  { id: "HDDQTRoi3czO5fXZ8ipc", name: "Smart Home Services" },
  { id: "HFRULkNe3AuHbjJmHZdq", name: "Cafe" },
  { id: "IBpJbb30FtbkKSY2Ppcm", name: "Pet Care" },
  { id: "Io9zenjSvFuj5VNFc3Cc", name: "Writing and Translation" },
  { id: "KkO0X3bMJo9n5JP7oDcI", name: "Food" },
  { id: "MvDRpgufD2fss3HtbdvH", name: "Bakery" },
  { id: "N2nEu3NodUh52axkPoLp", name: "Toys and Hobbies" },
  { id: "N875BADD6OYVRYrCyoDq", name: "Engineering Services" },
  { id: "Ne8QBIGBCRtCHCSzrZtA", name: "Finance and Accounting" },
  { id: "Noxw1AaGejYt2yGp6q2R", name: "Stationary Supplies" },
  { id: "OeZXhLGG5XyFwVmyN4jk", name: "Video Games" },
  { id: "P1TW52I68OoS189DhQMP", name: "Fast Food" },
  { id: "P2WaoulRfR4SxpjLu9b6", name: "Gaming" },
  { id: "RY97pxjAKl1dvGtbcIfg", name: "Vehicle Services" },
  { id: "S6dPSRqNr9KhB72dgKir", name: "Architecture and Interior Designer" },
  { id: "T5C5SXuQ9nJx3S3bHDdA", name: "Grocery and Gourmet Products" },
  { id: "TEuMtW74y8x1s3qrHTMV", name: "Digital Marketing" },
  { id: "TM1P23fnBGIUk6upleWd", name: "School Supplies" },
  { id: "U1quPN2DSqRRRIiTd970", name: "Liquor and Spirits" },
  { id: "UDmv4eqBTOHbqh0Lmtao", name: "Farm Supply" },
  { id: "UPaZBljMoUx1WapHNGoS", name: "Fashion and Style" },
  { id: "UccZcexr1SQfOZFmwfss", name: "Photography" },
  { id: "V5CifZKwdR4Ic5JDFtug", name: "Home Maintenance" },
  { id: "VCqcTNfleYbct8dKgBhP", name: "Pan Cake" },
  { id: "Xp7c1qMwshR0CwzOvbxD", name: "Electronics" },
  { id: "Yiukme4Bz3uYfE2aYisi", name: "Digital Content" },
  { id: "ZBdQdaHg33A30p4cIu5b", name: "Vehicle Accessories" },
  { id: "aFDH7bSnYre4BnmWiUZ9", name: " Jewelry" },
  { id: "c6DgNhQIjoEABX6Hej2p", name: "Tech and Programming" },
  { id: "cd211unSdhintCM29xCd", name: "Cosmetics" },
  { id: "d8UISk6j0RXfhkIY1gV4", name: "Hardware Store and Services " },
  { id: "dbB0pW1JxSBGDaXdFTuC", name: "Bakery Essentials" },
  { id: "hASrzavBu37bB9ldPPVw", name: "Veterinary Services" },
  { id: "jELjgjfharBpUUXq9s9C", name: "Industry" },
  { id: "kOCgkJ4WdTTEeiuWAZgQ", name: "Digital Art" },
  { id: "kUOd3I1hfQkkZWKCI14Q", name: "Healthcare Service" },
  { id: "lm2JrKHwjQyQdBtCOzC9", name: "Cooking" },
  { id: "m1Gc7lNe9pEDpy9bdUf5", name: "Books" },
  { id: "nKyJeBMACrbZQOc5TMib", name: "Cloud Kitchen" },
  { id: "poOZvWsnlKrLIbNJ6K0z", name: "Farming Essentials" },
  { id: "q51TFUt5ClISeCewb57i", name: "Illustration Service" },
  { id: "rG0CZlgOsXM2hCUM7ZpK", name: "Industry Essentials" },
  { id: "rniKz3kxpj3U5x39tceR", name: "Social Media" },
  { id: "shor4eMnxHGD0ZdIMAvk", name: "Music" },
  { id: "stE1SDJ8nL0tmfES6VUV", name: "Cooking Essentials" },
  { id: "t8PySh3yKaeI2C0lU1Bg", name: "Tools and Utility" },
  { id: "tMN5Wct7Kph2ydShmHAS", name: "Influencer" },
  { id: "u2lnAjDo23xz9rBJLZG6", name: "Cleaning Services" },
  { id: "unOSNdbcSonvejn8YOsG", name: "Skill Courses" },
  { id: "vBspyWDtZjZI3ZYGqAAs", name: "Government Services" },
  { id: "wwJB8V7SOjcK1rdtVHdj", name: "Parlour and Grooming" },
  { id: "xCPurAtz75gMifvIxlW3", name: "Animation aVideo" },
  { id: "xPMdFsmL51DCdrrWCyCQ", name: "Art and Craft" },
  { id: "y63FNDNSNbpGlDDfYk6F", name: "Education and Training" },
  { id: "zDhj91DFo3nc4HEHq8Iq", name: "Tattooing" },
];

let categoryArray = [];
categories.forEach((category) => {
  const newCat = {
    value: category.name,
    label: category.name,
  };
  categoryArray.push(newCat);
});

export default categoryArray;
